name: Continuous integration and deployment
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write
  attestations: write

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Env
        run: cp .env_template .env

      - name: Build
        run: make all

      - name: Lint
        run: make lint

      - name: Check
        run: make check

      - name: Migrate
        run: make migrate

      - name: Test
        run: make test

      - name: Generate mock data
        run: make generate_mock_data

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to registry
        run: |
          docker tag django-ninja-project:latest ${{ env.REGISTRY }}/project/django-ninja-project:$GITHUB_SHA
          docker push ${{ env.REGISTRY }}/project/django-ninja-project:$GITHUB_SHA
          echo "Image pushed to ${{ env.REGISTRY }}/project/django-ninja-project:$GITHUB_SHA"

      - name: Restart server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.REGISTRY }} --username ${{ github.actor }} --password-stdin
            docker stop django-ninja-project 1> /dev/null 2>&1
            docker rm django-ninja-project 1> /dev/null 2>&1
            docker rmi $(docker images | grep 'project') 1> /dev/null 2>&1
            docker pull ${{ env.REGISTRY }}/project/django-ninja-project:${{ github.sha }}
            
            echo "# Autogenerated .env file" > .env
            echo "DEBUG=${{ secrets.DEBUG }}" >> .env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
            echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> .env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
            echo "EMAIL_USE_TLS=${{ secrets.EMAIL_USE_TLS }}" >> .env
            echo "EMAIL_HOST=${{ secrets.EMAIL_HOST }}" >> .env
            echo "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" >> .env
            echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> .env
            echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env
            echo "EMAIL_BACKEND=${{ secrets.EMAIL_BACKEND }}" >> .env
            echo "DEFAULT_FROM_EMAIL=${{ secrets.DEFAULT_FROM_EMAIL }}" >> .env
            
            docker run --rm --name django-ninja-project-migrator --env-file .env ${{ env.REGISTRY }}/project/django-ninja-project:${{ github.sha }} ./manage.py migrate
            
            docker run --rm --name django-ninja-project-collectstatic --env-file .env -v /var/www/api/static:/project/collectstatic ${{ env.REGISTRY }}/project/django-ninja-project:${{ github.sha }} ./manage.py collectstatic --noinput
            
            docker run -d --name django-ninja-project --env-file .env --restart on-failure --net host -v /var/www/api/media:/project/media --log-driver=loki --log-opt loki-url="http://localhost:3100/loki/api/v1/push" ${{ env.REGISTRY }}/project/django-ninja-project:${{ github.sha }} gunicorn --bind 0.0.0.0:8000 project.wsgi:application
